Fix #145, no correct Rust compilation
conda-forge/lipyphilic-feedstock pull request #14
Opened 2024-12-03 14:34 UTC by RubenChM

Fix for [#145](https://github.com/p-j-smith/lipyphilic/issues/145). With this conda will build different packages 
for at least the python versions 3.10 and 3.11, with the correct compiled version of lipyferric.

Also with [numpy 2.0](https://numpy.org/devdocs/release/2.0.0-notes.html), there has been some breaking changes that makes the importing of lipyphilic fail like:
` 
  File "/home/rchaves/miniforge3/envs/test/lib/python3.12/site-packages/numpy/__init__.py", line 400, in __getattr__
    raise AttributeError(AttributeError: np.NaN was removed in the NumPy 2.0 release. Use np.nan instead.
`

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-12-03 14:35 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I failed to even lint the recipe, probably because of a conda-smithy bug :cry:. This likely indicates a problem in your `meta.yaml`, though. To get a traceback to help figure out what's going on, install conda-smithy and run `conda smithy recipe-lint --conda-forge .` from the recipe directory. You can also examine the [workflow logs](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12141872503) for more detail.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12141872503](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12141872503). Examine the logs at this URL for more detail.</sub>

2024-12-03 15:12 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

I do have some suggestions for making it better though...


For **recipe/meta.yaml**:

 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12142544153](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12142544153). Examine the logs at this URL for more detail.</sub>

2024-12-03 15:55 UTC, RubenChM commented
@conda-forge-admin, please rerender

2024-12-04 09:12 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found some lint.

Here's what I've got...


For **recipe/meta.yaml**:

 * ❌ Selectors are suggested to take a ``<two spaces>#<one space>[<expression>]`` form. See lines [18]

For **recipe/meta.yaml**:

 * ℹ️ PyPI default URL is now pypi.org, and not pypi.io. You may want to update the default source url.


<sub>This message was generated by GitHub Actions workflow run [https://github.com/conda-forge/conda-forge-webservices/actions/runs/12156500158](https://github.com/conda-forge/conda-forge-webservices/actions/runs/12156500158). Examine the logs at this URL for more detail.</sub>

2024-12-04 09:16 UTC, conda-forge-admin commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe/meta.yaml```) and found it was in an excellent condition.

2024-12-04 13:26 UTC, p-j-smith requested changes
Thanks for fixing this @RubenChM!

Just one question around the Python versions used for building. Also, would you like to add yourself to the list of maintainers for this feedstock (no worries if not)

2024-12-04 13:26 UTC, p-j-smith commented on recipe/meta.yaml
> +    - python >=3.10,<3.12                    # [build_platform != target_platform]
```suggestion
    - python >=3.10,<3.13                    # [build_platform != target_platform]
```
Is there an issue with building with 3.12?

2024-12-04 14:53 UTC, RubenChM commented on recipe/meta.yaml
> +    - python >=3.10,<3.12                    # [build_platform != target_platform]
There is not! 
It is actually building for 3.12 and it even passed the [tests](https://github.com/conda-forge/lipyphilic-feedstock/pull/14/checks?check_run_id=33900768761) for every OS.
It took me some time to realize the build variants are the ones created at .ci_support with `conda smithy rerender` and this add variants from a few places:
```
Adding in variants from internal_defaults
Adding in variants from /home/rchaves/.cache/conda-smithy/conda_build_config.yaml
Adding in variants from /home/rchaves/repo/lipyphilic-feedstock/recipe/conda_build_config.yaml
Adding in variants from argument_variants
```
I am not sure why it worked with the `<3.12`  in the build requirements, but it is nice having it at least for clarity.

2024-12-04 14:55 UTC, RubenChM commented
Yes, you can add me! I am doing some membrane analysis right now, so I may help with the library.

2024-12-04 15:52 UTC, p-j-smith approved these changes
> Yes, you can add me! I am doing some membrane analysis right now, so I may help with the library.

oh cool 😄 

Thanks again for the fix!

2024-12-04 15:52 UTC, merged